/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.tabelas.ClienteTableModel;

/**
 *
 * @author Nelson Matsinhe
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCliente() {
        
     */
    public TelaCliente() {
        
            initComponents();
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0, 0, 0));
            BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
            ui.setNorthPane(null);
            this.setBorder(null);
            //txtID.setFocusable(false);
            habilitarFormulario(false);
             carregarGrade();
            
            
            
    }
    
   

    @SuppressWarnings("unchecked")

    Color d = new Color(255, 0, 51);
    Color f = new Color(219, 220, 252);

     private Cliente cliente = null;
    private ClienteDAO clienteDAO = new ClienteDAO();
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        telefone = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        lblMessagem1 = new javax.swing.JLabel();
        lblMessagem2 = new javax.swing.JLabel();
        lblMessagem = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblMessagem3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spGrade = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(1270, 890));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setToolTipText("");
        jPanel7.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(45, 229, 36, 15);

        txtnome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnome.setMinimumSize(null);
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });
        jPanel7.add(txtnome);
        txtnome.setBounds(99, 218, 342, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Endereco:");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(25, 303, 56, 15);

        txtendereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtendereco.setText("  ");
        txtendereco.setMinimumSize(null);
        txtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoActionPerformed(evt);
            }
        });
        txtendereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtenderecoKeyPressed(evt);
            }
        });
        jPanel7.add(txtendereco);
        txtendereco.setBounds(99, 292, 342, 34);

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+225#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setMinimumSize(null);
        telefone.setPreferredSize(new java.awt.Dimension(200, 28));
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefoneKeyPressed(evt);
            }
        });
        jPanel7.add(telefone);
        telefone.setBounds(99, 373, 345, 38);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Id:");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(66, 172, 15, 15);

        lblMessagem1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lblMessagem1.setForeground(new java.awt.Color(255, 0, 51));
        lblMessagem1.setText(" ");
        jPanel7.add(lblMessagem1);
        lblMessagem1.setBounds(100, 250, 342, 40);

        lblMessagem2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        lblMessagem2.setForeground(new java.awt.Color(255, 0, 51));
        lblMessagem2.setText(" ");
        jPanel7.add(lblMessagem2);
        lblMessagem2.setBounds(100, 340, 334, 27);

        lblMessagem.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        lblMessagem.setForeground(new java.awt.Color(255, 0, 51));
        lblMessagem.setText(" ");
        jPanel7.add(lblMessagem);
        lblMessagem.setBounds(217, 664, 355, 25);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefone:");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(28, 384, 53, 15);

        lblMessagem3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        lblMessagem3.setForeground(new java.awt.Color(255, 0, 51));
        lblMessagem3.setText(" ");
        jPanel7.add(lblMessagem3);
        lblMessagem3.setBounds(99, 337, 319, 30);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8_add_32px.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel3.add(btNovo);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8_save_32px.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setFocusable(false);
        btSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel3.add(btSalvar);

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8_edit_property_22px.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setFocusable(false);
        btEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEditar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btEditar);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8_cancel_32px.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setFocusable(false);
        btExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btExcluir);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8_cancel_32px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        jPanel7.add(jPanel3);
        jPanel3.setBounds(10, 520, 480, 70);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel7.add(txtID);
        txtID.setBounds(100, 160, 340, 30);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 500, 620));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro do Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 90));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new ClienteTableModel());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        spGrade.setViewportView(jTable1);

        getContentPane().add(spGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 340, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
     int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o cliente " + cliente + "?");
        if (opcao == 0) {
            try {
                clienteDAO.excluir(cliente);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            habilitarFormulario(false);
            
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
         if (validarFormulario()) {
             cliente.setId((txtID.getText()));
             cliente.setNome(txtnome.getText());
                cliente.setEndereco(txtendereco.getText());
                cliente.setTelefone(telefone.getText());

            if (cliente.getId()== 0) {
               
                try {
                    clienteDAO.alterar(cliente);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar o cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            habilitarFormulario(false);
        }
        
        
                 
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
       
           if (validarFormulario()) {
             cliente.setNome(txtnome.getText());
                cliente.setEndereco(txtendereco.getText());
                cliente.setTelefone(telefone.getText());

            if (cliente.getId()== 0) {
                try {
                    clienteDAO.inserir(cliente);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao inserir o cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                try {
                    clienteDAO.alterar(cliente);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar o cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            habilitarFormulario(false);
           
        }
        
        
        
        
     
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
       cliente = new Cliente();
        habilitarFormulario(true);
        btExcluir.setEnabled(false);
                                  
    }//GEN-LAST:event_btNovoActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        validarFormulario();
    }//GEN-LAST:event_telefoneActionPerformed

    private void txtenderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenderecoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (validarFormulario()) {
                telefone.requestFocusInWindow();
            }


        }
    }//GEN-LAST:event_txtenderecoKeyPressed

    private void txtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoActionPerformed
        if (!txtendereco.getText().contains("@") || !txtendereco.getText().contains(".") || !txtendereco.getText().contains("com")) {
            txtendereco.setBackground(d);
            txtendereco.requestFocus();
        } else {
            txtendereco.setBackground(f);
            telefone.requestFocus();
        }
    }//GEN-LAST:event_txtenderecoActionPerformed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            validarFormulario();

            // End of variables declaration
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed

        if (txtnome.getText().isEmpty()) {
            txtnome.requestFocus();
            txtnome.setBackground(d);

        } else {
            txtnome.setBackground(f);
            txtendereco.setBackground(f);
        }
    }//GEN-LAST:event_txtnomeActionPerformed

    private void telefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER) {
            validarFormulario();

            // End of variables declaration
        }
    }//GEN-LAST:event_telefoneKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void habilitarFormulario(boolean ativo) {
        btNovo.setEnabled(!ativo);
        btSalvar.setEnabled(ativo);
        btExcluir.setEnabled(ativo);
        btNovo.setEnabled(!ativo);
        btSalvar.setEnabled(ativo);
        btEditar.setEnabled(ativo);;
        btExcluir.setEnabled(ativo);
        txtID.setEnabled(ativo);
        txtnome.setEnabled(ativo);
        txtendereco.setEnabled(ativo);
        telefone.setEnabled(ativo);
        btnCancelar.setEnabled(ativo);
        jTable1.setEnabled(!ativo);

        if (!ativo) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {
        cliente = null;
      
        txtID.setText("");
        txtnome.setText("");
        txtendereco.setText("");
        telefone.setText("");
    }
    /**
     * Validacao dos campos
     

    /**
     * Metido que valida r o formulario
     *
     * @return true se todos os camps estiver validados
     */
  
    private boolean validarFormulario() {
        if (txtnome.getText().isEmpty()) {
        txtnome.requestFocus();
        lblMessagem1.setText("Preencha o campo com um nome");
        return false;
    } else if (txtnome.getText().trim().length() < 2) {
        txtnome.setBackground(d);
        txtnome.requestFocus();
        lblMessagem1.setText("Preencha o campo com um nome válido");
        return false;
    } else {
        txtnome.setBackground(f);
         lblMessagem1.setText("");
    }

    if (txtendereco.getText().isEmpty()) {
      //  txtendereco.setBackground(d);
        txtendereco.requestFocus();
        lblMessagem2.setText("Preencha o campo com um endereço");
        return false;
    } else if (txtendereco.getText().trim().length() < 2) {
        txtendereco.setBackground(d);
        txtendereco.requestFocus();
        lblMessagem2.setText("Preencha o campo com um endereço válido");
        return false;
    } else {
        txtendereco.setBackground(f);
        telefone.requestFocusInWindow(); // Solicita o foco no campo telefone
        lblMessagem2.setText("");
    }

    if (telefone.getText().isEmpty()) {
       // telefone.setBackground(d);
        telefone.requestFocusInWindow();
        lblMessagem3.setText("Preencha o campo com um celular válido");
        return false;}
        else if (telefone.getText().trim().length() < 2) {
        telefone.setBackground(d);
       telefone.requestFocus();
        lblMessagem2.setText("Preencha o campo com um Telefone válido");
        return false;
    } else {
        telefone.setBackground(f);
        lblMessagem3.setText("");
    }
    return true;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMessagem;
    private javax.swing.JLabel lblMessagem1;
    private javax.swing.JLabel lblMessagem2;
    private javax.swing.JLabel lblMessagem3;
    private javax.swing.JScrollPane spGrade;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
