package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import controller.Criptografar;
import controller.LoginDAO;
import controller.UsuarioDAO;
import java.awt.Color;
import static java.awt.Color.green;
import static java.awt.Color.red;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import model.Usuario;
import view.TelaMenuAdmin;

/**
 *
 * @author Nelson Matsinhe
 */
public class TelaLogin extends javax.swing.JFrame {
//TelaMenu menu=new TelaMenu();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        iniciarFormulario();
        login.setEnabled(false); // Desabilita o botão inicialmente

    }
    Usuario usuario = new Usuario();
    Color red = new Color(255, 0, 51);
    Color green = new Color(0, 204, 0);
    // Método para validar o campo "User Name"

    public boolean validarUserName(String userName) {
        // Regex: Aceita apenas letras, números e pelo menos 2 caracteres
        return userName.matches("[a-zA-Z0-9]{2,}");
    }

    public boolean camposValidos() {
        String senha = new String(txsenha.getPassword());
        String userName = txtUsuario.getText().trim();

        if (userName.isEmpty() || !validarUserName(userName)) {
            txtUsuario.requestFocus();
            txtUsuario.setBorder(BorderFactory.createLineBorder(red)); // Borda vermelha se inválido
            lblMessagem1.setText("Preencha o campo User Name válido (somente letras e números)");
            return false;
        } else {
            txtUsuario.setBorder(BorderFactory.createLineBorder(green)); // Borda verde se válido
            lblMessagem1.setText("");
        }

        if (senha.isEmpty() || senha.length() <= 4) {
            txsenha.setBorder(BorderFactory.createLineBorder(red)); // Borda vermelha se inválido
            lblMessagem1.setText("A senha deve ter mais de 4 caracteres");
            txsenha.requestFocus();
            return false;
        } else {
            txsenha.setBorder(BorderFactory.createLineBorder(green)); // Borda verde se válido
            lblMessagem1.setText("");
        }

        lblMessagem1.setText("");
        return true;
    }

// Habilitar botão se ambos os campos forem válidos
    public void habilitarBotaoSeValido() {
        boolean camposSaoValidos = camposValidos();
        login.setEnabled(camposSaoValidos);
    }
// Inicializa o formulário e adiciona os ouvintes

    public void iniciarFormulario() {
        txtUsuario.requestFocus(); // Coloca o foco no campo txtUsuario ao iniciar

        // Modifica o ouvinte do campo txtUsuario
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    // evt.consume(); // Impede o comportamento padrão da tecla Enter
                    if (camposValidos()) {
                        txsenha.requestFocus(); // Move o foco para a senha APENAS ao pressionar Enter
                    }
                }
                habilitarBotaoSeValido(); // Verifica a validade a cada tecla pressionada
            }
        });

        // Modifica o ouvinte do campo txsenha
        txsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    // evt.consume(); // Impede o comportamento padrão da tecla Enter
                    if (camposValidos()) {
                        login.requestFocus(); // Move o foco para o botão APENAS ao pressionar Enter
                    }
                }
                habilitarBotaoSeValido(); // Verifica a validade a cada tecla pressionada
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        txsenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblMessagem1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        lblMessagem.setForeground(new java.awt.Color(255, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(2, 2, 2, 2));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(0, 0, 51));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("ENTRAR");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 318, 59));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        txsenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txsenha.setForeground(new java.awt.Color(102, 102, 102));
        txsenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 51)));
        txsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txsenhaActionPerformed(evt);
            }
        });
        txsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txsenhaKeyPressed(evt);
            }
        });
        jPanel2.add(txsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 314, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Usuario");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 51)));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 318, 35));

        lblMessagem1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblMessagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 390, 26));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 420, 540));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 410, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 830, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txsenhaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume(); // Impede o comportamento padrão da tecla Enter
            if (camposValidos()) {
                login.requestFocus();
                lblMessagem1.setText("");
            }
        }
    }//GEN-LAST:event_txsenhaKeyPressed

    private void txsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txsenhaActionPerformed

    }//GEN-LAST:event_txsenhaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txsenha.setEchoChar((char) 0);
        } else {
            txsenha.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        if (!camposValidos()) {
            return;  // Não faz nada se os campos não são válidos
        }

        LoginDAO loginDAO = new LoginDAO();
        String userName = txtUsuario.getText();
        String senha = String.valueOf(txsenha.getPassword());

        Usuario usuarioAutenticado = loginDAO.autenticar(userName, senha);

        if (usuarioAutenticado != null) {
            String perfil = loginDAO.verificarPerfil(usuarioAutenticado);
            lblMessagem1.setText("Usuário autenticado como: " + perfil);

            // Exibe mensagem de boas-vindas de acordo com o perfil
            if (perfil.equals("Administrador")) {
                lblMessagem1.setText("Bem-vindo Admin");
                TelaMenuAdmin a = new TelaMenuAdmin();

                a.setVisible(true);
                this.dispose();
            } else if (perfil.equals("SuperAdmin")) {

                lblMessagem1.setText("Bem-vindo SuperAdmin");
            } else if (perfil.equals("User")) {

                lblMessagem1.setText("Bem-vindo User");
                TelaMenuAdmin U = new TelaMenuAdmin();
                U.setVisible(true);
                this.dispose();
            }
        } else {
            // Se falhar a autenticação, exibe mensagem de erro
            lblMessagem1.setText("Falha na autenticação. Verifique o nome de usuário e a senha.");
        }

    }//GEN-LAST:event_loginActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume(); // Impede o comportamento padrão da tecla Enter
            if (camposValidos()) {
                txsenha.requestFocus();
                lblMessagem.setText("");
            }
        }


    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (!camposValidos()) {
                return;  // Não faz nada se os campos não são válidos
            }

            LoginDAO loginDAO = new LoginDAO();
            String userName = txtUsuario.getText();
            String senha = String.valueOf(txsenha.getPassword());

            Usuario usuarioAutenticado = loginDAO.autenticar(userName, senha);

            if (usuarioAutenticado != null) {
                String perfil = loginDAO.verificarPerfil(usuarioAutenticado);
                lblMessagem1.setText("Usuário autenticado como: " + perfil);

                // Exibe mensagem de boas-vindas de acordo com o perfil
                if (perfil.equals("Admin")) {
                    lblMessagem1.setText("Bem-vindo Admin");
                    TelaMenuAdmin a = new TelaMenuAdmin();

                    a.setVisible(true);
                    this.dispose();
                } else if (perfil.equals("SuperAdmin")) {

                    lblMessagem1.setText("Bem-vindo SuperAdmin");
                } else if (perfil.equals("User")) {

                    lblMessagem1.setText("Bem-vindo User");
                    TelaMenuAdmin U = new TelaMenuAdmin();
                    U.setVisible(true);
                    this.dispose();
                }
            } else {
                // Se falhar a autenticação, exibe mensagem de erro
                lblMessagem1.setText("Falha na autenticação. Verifique o nome de usuário e a senha.");
            }
        }


    }//GEN-LAST:event_loginKeyPressed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased

        habilitarBotaoSeValido();
    }//GEN-LAST:event_txtUsuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMessagem;
    private javax.swing.JLabel lblMessagem1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField txsenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
