/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Criptografar;
import controller.MaterialDAO;
import controller.UsuarioDAO;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Fornecedor;
import model.Funcionario;
import model.Material;
import model.Usuario;
import model.tabelas.MaterialTableModel;
import model.tabelas.UsuarioTableModel;

//import model.Produto;
/**
 * class tela de registros das produto
 *
 * @author Nelson Matsinhe
 */
public class TelaMaterial extends javax.swing.JInternalFrame {

    /**
     * Creates new form Produto
     */
    //GenericDAO prod = new GenericDAO<>(Produto.class);
    public TelaMaterial() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        habilitarFormulario(false);
        carregarGrade();

       txtNome.requestFocus();

        // Botão Novo habilita o formulário
        btNovo.addActionListener(e -> habilitarFormulario(true));

        // Ação do botão Salvar
        btSalvar.addActionListener(e -> {
            if (validarFormulario()) {
                //    btEditarActionPerformed();
            }
        });

        // Ação do botão Editar
        // btEditar.addActionListener(e -> btEditarActionPerformed());
        // Validação ao mudar os campos
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                habilitarSalvar();
            }
        });

        TbMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectRegistryTable();
            }
        });
    }
    /**
     *
     * as cores da campos
     */
    Color d = new Color(255, 0, 51);
    Color f = new Color(219, 220, 252);

    MaterialDAO materialDAO = new MaterialDAO();
    Material material = new Material();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estadoGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbMaterial = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lblMessagem = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JFormattedTextField();
        lblMessagem1 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        btnFornecedor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbMaterial1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btCancelar1 = new javax.swing.JButton();
        btNovo1 = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        btEditar1 = new javax.swing.JButton();
        btExcluir1 = new javax.swing.JButton();
        lblMessagem2 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtQuantidade1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUnidade1 = new javax.swing.JFormattedTextField();
        lblMessagem3 = new javax.swing.JLabel();
        txtPreco1 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFornecedor1 = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        btnFornecedor1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registro de Maquina");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 102, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 146, 1, -1));

        TbMaterial.setModel(new MaterialTableModel());
        TbMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbMaterial);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 201, 761, 254));

        btCancelar.setText("Cancelar");
        btCancelar.setFocusable(false);
        btCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btNovo.setPreferredSize(new java.awt.Dimension(64, 22));
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.setFocusable(false);
        btSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btSalvar.setPreferredSize(new java.awt.Dimension(64, 22));
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.setFocusable(false);
        btEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEditar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btEditar.setPreferredSize(new java.awt.Dimension(64, 22));
        btEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setFocusable(false);
        btExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btExcluir.setPreferredSize(new java.awt.Dimension(64, 22));
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 201, -1, -1));
        jPanel6.add(lblMessagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 529, 23));

        txtID.setPreferredSize(new java.awt.Dimension(250, 30));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel6.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        txtNome.setPreferredSize(new java.awt.Dimension(250, 30));
        txtNome.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        jPanel6.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        txtQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000000, 1));
        txtQuantidade.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel6.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("quantidade");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Unidade");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        txtUnidade.setColumns(10);
        txtUnidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtUnidade.setPreferredSize(new java.awt.Dimension(250, 30));
        txtUnidade.setValue(new Double(0));
        txtUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadeActionPerformed(evt);
            }
        });
        jPanel6.add(txtUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 290, -1));
        jPanel6.add(lblMessagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        txtPreco.setColumns(10);
        txtPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPreco.setPreferredSize(new java.awt.Dimension(250, 30));
        txtPreco.setValue(new Double(0));
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        jPanel6.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 300, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Preco");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        txtFornecedor.setEditable(false);
        txtFornecedor.setColumns(25);
        txtFornecedor.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel6.add(txtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("fornecedor");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8-plus-29.png"))); // NOI18N
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });
        jPanel6.add(btnFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, -1));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBackground(new java.awt.Color(51, 102, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 146, 1, -1));

        TbMaterial1.setModel(new MaterialTableModel());
        TbMaterial1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbMaterial1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TbMaterial1);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 761, 254));

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 245));

        btCancelar1.setText("Cancelar");
        btCancelar1.setFocusable(false);
        btCancelar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btCancelar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });

        btNovo1.setText("Novo");
        btNovo1.setFocusable(false);
        btNovo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btNovo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btNovo1.setPreferredSize(new java.awt.Dimension(64, 22));
        btNovo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo1ActionPerformed(evt);
            }
        });

        btSalvar1.setText("Salvar");
        btSalvar1.setFocusable(false);
        btSalvar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSalvar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btSalvar1.setPreferredSize(new java.awt.Dimension(64, 22));
        btSalvar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });

        btEditar1.setText("Editar");
        btEditar1.setFocusable(false);
        btEditar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEditar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEditar1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btEditar1.setPreferredSize(new java.awt.Dimension(64, 22));
        btEditar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditar1ActionPerformed(evt);
            }
        });

        btExcluir1.setText("Excluir");
        btExcluir1.setFocusable(false);
        btExcluir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btExcluir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btExcluir1.setPreferredSize(new java.awt.Dimension(64, 22));
        btExcluir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btExcluir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btEditar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btSalvar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btEditar1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btExcluir1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel7.add(lblMessagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 529, 23));

        txtID1.setPreferredSize(new java.awt.Dimension(300, 30));
        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });
        jPanel7.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 300, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        txtNome1.setPreferredSize(new java.awt.Dimension(300, 30));
        txtNome1.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });
        txtNome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNome1KeyPressed(evt);
            }
        });
        jPanel7.add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 300, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nome:");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        txtQuantidade1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000000, 1));
        txtQuantidade1.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel7.add(txtQuantidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("quantidade");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Unidade");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        txtUnidade1.setColumns(10);
        txtUnidade1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtUnidade1.setPreferredSize(new java.awt.Dimension(300, 30));
        txtUnidade1.setValue(new Double(0));
        txtUnidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidade1ActionPerformed(evt);
            }
        });
        jPanel7.add(txtUnidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 300, 30));
        jPanel7.add(lblMessagem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        txtPreco1.setColumns(10);
        txtPreco1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPreco1.setPreferredSize(new java.awt.Dimension(300, 30));
        txtPreco1.setValue(new Double(0));
        txtPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreco1ActionPerformed(evt);
            }
        });
        jPanel7.add(txtPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 300, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Preco");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        txtFornecedor1.setEditable(false);
        txtFornecedor1.setColumns(25);
        txtFornecedor1.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel7.add(txtFornecedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 300, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("fornecedor");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        btnFornecedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8-plus-29.png"))); // NOI18N
        btnFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedor1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnFornecedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(627, 86));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registro de Maquina");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 960, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void TbMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbMaterialMouseClicked

    }//GEN-LAST:event_TbMaterialMouseClicked

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed

    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (validarFormulario()) {
            // Certifique-se de que o material foi instanciado corretamente
            if (material == null) {
                material = new Material();
            }

            material.setNome(txtNome.getText());
            material.setQuantidade(Integer.parseInt((String) txtQuantidade.getValue()));
            material.setUnidade(txtUnidade.getText());
            material.setPreco(Double.parseDouble(txtPreco.getText()));
            material.setFornecedor((Fornecedor) txtFornecedor.getValue());

            // Adicione aqui a lógica para definir o fornecedor, se necessário
            // Verificar se o id é nulo e inicializá-lo se for o caso
            if (material.getId() == null) {
                material.setId(0L);  // Define o id como 0 (novo material)
            }

            // Operação de salvar ou atualizar o material
            if (material.getId() == 0) {
                try {
                    materialDAO.salvar(material);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao inserir o material.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                // Código para atualizar o material, caso seja necessário
            }

            habilitarFormulario(false);
            carregarGrade();
            limpaFormulario();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (validarFormulario()) {
            Long id;
            try {
                id = Long.parseLong(txtID.getText()); // Converte o ID de String para Long
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Material material = materialDAO.buscarPorId(id); // Agora busca usando o ID Long
            if (material != null) {
                material.setNome(txtNome.getText());
                material.setQuantidade(Integer.parseInt((String) txtQuantidade.getValue()));
                material.setUnidade(txtUnidade.getText());
                material.setPreco(Double.parseDouble(txtPreco.getText()));
                material.setFornecedor((Fornecedor) txtFornecedor.getValue());

                try {
                    materialDAO.atualizar(material); // Atualiza o material
                    JOptionPane.showMessageDialog(this, "Material atualizado com sucesso.");
                    limpaFormulario();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar o material.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }

                habilitarFormulario(false);
                carregarGrade();
            } else {
                JOptionPane.showMessageDialog(this, "Material não encontrado para edição.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Formulário inválido. Verifique os campos.");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (!txtID.getText().isEmpty()) {
            Long id = Long.valueOf(txtID.getText());

            int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este material?", "Confirmação", JOptionPane.YES_NO_OPTION);

            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    materialDAO.remover(id);  // Desativa o material
                    JOptionPane.showMessageDialog(this, "Material desativado com sucesso.");
                } catch (HeadlessException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao desativar o material.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }

                habilitarFormulario(false);
                carregarGrade();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um material para excluir.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            validarFormulario();

            // End of variables declaration
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        BuscaFornecedor buscaUsuario = new BuscaFornecedor(this);
        buscaUsuario.setVisible(true);
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void TbMaterial1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbMaterial1MouseClicked

    }//GEN-LAST:event_TbMaterial1MouseClicked

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo1ActionPerformed

    }//GEN-LAST:event_btNovo1ActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        if (validarFormulario()) {
            // Certifique-se de que o material foi instanciado corretamente
            if (material == null) {
                material = new Material();
            }

            material.setNome(txtNome.getText());
            material.setQuantidade(Integer.parseInt((String) txtQuantidade.getValue()));
            material.setUnidade(txtUnidade.getText());
            material.setPreco(Double.parseDouble(txtPreco.getText()));
            material.setFornecedor((Fornecedor) txtFornecedor.getValue());

            // Adicione aqui a lógica para definir o fornecedor, se necessário
            // Verificar se o id é nulo e inicializá-lo se for o caso
            if (material.getId() == null) {
                material.setId(0L);  // Define o id como 0 (novo material)
            }

            // Operação de salvar ou atualizar o material
            if (material.getId() == 0) {
                try {
                    materialDAO.salvar(material);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao inserir o material.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                // Código para atualizar o material, caso seja necessário
            }

            habilitarFormulario(false);
            carregarGrade();
            limpaFormulario();
        }
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void btEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditar1ActionPerformed
        if (validarFormulario()) {
            Long id;
            try {
                id = Long.parseLong(txtID.getText()); // Converte o ID de String para Long
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Material material = materialDAO.buscarPorId(id); // Agora busca usando o ID Long
            if (material != null) {
                material.setNome(txtNome.getText());
                material.setQuantidade(Integer.parseInt((String) txtQuantidade.getValue()));
                material.setUnidade(txtUnidade.getText());
                material.setPreco(Double.parseDouble(txtPreco.getText()));
                material.setFornecedor((Fornecedor) txtFornecedor.getValue());

                try {
                    materialDAO.atualizar(material); // Atualiza o material
                    JOptionPane.showMessageDialog(this, "Material atualizado com sucesso.");
                    limpaFormulario();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar o material.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }

                habilitarFormulario(false);
                carregarGrade();
            } else {
                JOptionPane.showMessageDialog(this, "Material não encontrado para edição.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Formulário inválido. Verifique os campos.");
        }
    }//GEN-LAST:event_btEditar1ActionPerformed

    private void btExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir1ActionPerformed
        if (!txtID.getText().isEmpty()) {
            Long id = Long.valueOf(txtID.getText());

            int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este material?", "Confirmação", JOptionPane.YES_NO_OPTION);

            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    materialDAO.remover(id);  // Desativa o material
                    JOptionPane.showMessageDialog(this, "Material desativado com sucesso.");
                } catch (HeadlessException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao desativar o material.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }

                habilitarFormulario(false);
                carregarGrade();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um material para excluir.");
        }
    }//GEN-LAST:event_btExcluir1ActionPerformed

    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void txtNome1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNome1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            validarFormulario();

            // End of variables declaration
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1KeyPressed

    private void txtUnidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidade1ActionPerformed

    private void txtPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreco1ActionPerformed

    private void btnFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedor1ActionPerformed
        BuscaFornecedor buscaUsuario = new BuscaFornecedor(this);
        buscaUsuario.setVisible(true);
    }//GEN-LAST:event_btnFornecedor1ActionPerformed

    private void habilitarFormulario(boolean ativo) {
        btNovo.setEnabled(!ativo);               // Botão "Novo" desativado quando ativo
        btSalvar.setEnabled(ativo && validarFormulario()); // "Salvar" habilitado apenas se o formulário for válido
        btCancelar.setEnabled(ativo);            // Botão "Cancelar" habilitado quando ativo
        btExcluir.setEnabled(ativo);             // Botão "Excluir" habilitado quando ativo
        txtID.setEnabled(ativo);                 // Campo ID habilitado/desabilitado
        txtNome.setEnabled(ativo);               // Campo Nome habilitado/desabilitado
        txtQuantidade.setEnabled(ativo);               // Campo NUIT habilitado/desabilitado
        txtUnidade.setEnabled(ativo);              // Campo Email habilitado/desabilitado
        txtPreco.setEnabled(ativo);
        txtFornecedor.setEnabled(ativo);
        btEditar.setEnabled(TbMaterial.getSelectedRow() >= 0 && ativo); // Habilita "Editar" se houver linha selecionada

        TbMaterial.setEnabled(!ativo);         // Desabilita tabela quando formulário estiver ativo

        if (!ativo) {
            limpaFormulario();                   // Limpa o formulário se desativado
        }
    }

    private void limpaFormulario() {
        txtID.setText("");
        txtNome.setText("");
        //  txtQuantidade.setValue("");
        txtUnidade.setText("");
        txtPreco.setText("");
        txtFornecedor.setText("");
        lblMessagem.setText("");
    }

    private void habilitarSalvar() {
        btSalvar.setEnabled(validarFormulario());
    }

    private boolean validarFormulario() {
        Border borderError = BorderFactory.createLineBorder(Color.RED, 2);  // Borda vermelha para erros
        Border borderNormal = BorderFactory.createLineBorder(Color.GRAY, 1); // Borda normal

        boolean isValid = true;

        // Validação do campo Nome
        if (txtNome.getText().isEmpty()) {
            txtNome.setBorder(borderError);
            lblMessagem.setText("Preencha o campo com um nome.");
            txtNome.requestFocus();
            isValid = false;
        } else {
            txtNome.setBorder(borderNormal);
        }

        // Validação do campo Quantidade
        if (txtQuantidade.getValue() == null || txtQuantidade.getValue().toString().isEmpty()) {
            txtQuantidade.setBorder(borderError);
            lblMessagem.setText("Preencha o campo com uma quantidade.");
            txtQuantidade.requestFocus();
            isValid = false;
        } else {
            txtQuantidade.setBorder(borderNormal);
        }

        // Validação do campo Unidade
        if (txtUnidade.getText().isEmpty()) {
            txtUnidade.setBorder(borderError);
            lblMessagem.setText("Preencha o campo com uma unidade.");
            txtUnidade.requestFocus();
            isValid = false;
        } else {
            txtUnidade.setBorder(borderNormal);
        }

        // Validação do campo Preço
        if (txtPreco.getText().isEmpty()) {
            txtPreco.setBorder(borderError);
            lblMessagem.setText("Preencha o campo com um preço.");
            txtPreco.requestFocus();
            isValid = false;
        } else {
            txtPreco.setBorder(borderNormal);
        }

        return isValid;
    }

    public void selectRegistryTable() {
        int selectedRow = TbMaterial.getSelectedRow(); // Referência à tabela de materiais
        if (selectedRow != -1) {
            txtID.setText(TbMaterial.getValueAt(selectedRow, 0).toString());          // ID do material
            txtNome.setText(TbMaterial.getValueAt(selectedRow, 1).toString());        // Nome do material
            txtQuantidade.setValue(TbMaterial.getValueAt(selectedRow, 2).toString());  // Quantidade
            txtUnidade.setText(TbMaterial.getValueAt(selectedRow, 3).toString());     // Unidade de medida
            txtPreco.setText(TbMaterial.getValueAt(selectedRow, 4).toString());       // Preço
            txtFornecedor.setText(TbMaterial.getValueAt(selectedRow, 5).toString());  // Fornecedor

            habilitarFormulario(true); // Habilita o formulário para edição
        }
    }

    void setFornecedor(Fornecedor funcionario) {
        if (funcionario != null) {
            txtFornecedor.setValue(funcionario);
        } else {
            txtFornecedor.setText(""); // Caso o usuário seja nulo, limpar o campo
        }
    }

    private void carregarGrade() {
        MaterialTableModel tm = (MaterialTableModel) TbMaterial.getModel();
        try {
            tm.setDados(materialDAO.listarTodos());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbMaterial;
    private javax.swing.JTable TbMaterial1;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEditar1;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluir1;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btNovo1;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnFornecedor1;
    private javax.swing.ButtonGroup estadoGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMessagem;
    private javax.swing.JLabel lblMessagem1;
    private javax.swing.JLabel lblMessagem2;
    private javax.swing.JLabel lblMessagem3;
    private javax.swing.JFormattedTextField txtFornecedor;
    private javax.swing.JFormattedTextField txtFornecedor1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JFormattedTextField txtPreco1;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JSpinner txtQuantidade1;
    private javax.swing.JFormattedTextField txtUnidade;
    private javax.swing.JFormattedTextField txtUnidade1;
    // End of variables declaration//GEN-END:variables
}
